<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActualSubcategorySeeder extends Seeder
{
    /**
     * Run the master Subcategory database seeds.
     * Total records: 111
     */
    public function run(): void
    {
        $records = [
            [
                'id' => 1,
                'code' => 'FUR-KK',
                'name' => 'Kursi Kerja',
                'description' => 'Kursi kerja',
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:24:28',
                'updated_at' => '2026-04-08 08:24:28',
            ],
            [
                'id' => 2,
                'code' => 'FUR-MK',
                'name' => 'Meja Kerja',
                'description' => 'Warna abu-abu dan cream',
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:24:37',
                'updated_at' => '2026-04-08 08:24:37',
            ],
            [
                'id' => 3,
                'code' => 'FUR-LC',
                'name' => 'Laci Kerja',
                'description' => 'Warna cream dan abu-abu',
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:24:44',
                'updated_at' => '2026-04-08 08:24:44',
            ],
            [
                'id' => 4,
                'code' => 'FUR-LM',
                'name' => 'Lemari',
                'description' => 'Lemari dari thn 2011 - 2015',
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:24:57',
                'updated_at' => '2026-04-08 08:24:57',
            ],
            [
                'id' => 5,
                'code' => 'FUR-KP',
                'name' => 'Kursi Plastik',
                'description' => 'Kursi plastik warna cokelat',
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:25:03',
                'updated_at' => '2026-04-08 08:25:03',
            ],
            [
                'id' => 6,
                'code' => 'FUR-MB',
                'name' => 'Meja Bundar',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:25:10',
                'updated_at' => '2026-04-08 08:25:10',
            ],
            [
                'id' => 7,
                'code' => 'FUR-KT',
                'name' => 'Kursi Tamu',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:25:40',
                'updated_at' => '2026-04-08 08:25:40',
            ],
            [
                'id' => 8,
                'code' => 'FUR-MT',
                'name' => 'Meja Tamu',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 1,
                'created_at' => '2026-04-08 08:25:35',
                'updated_at' => '2026-04-08 08:25:35',
            ],
            [
                'id' => 9,
                'code' => 'ACC-AP',
                'name' => 'Apar',
                'description' => 'Apar',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:25:46',
                'updated_at' => '2026-04-08 08:25:46',
            ],
            [
                'id' => 10,
                'code' => 'ACC-WB',
                'name' => 'Whiteboard',
                'description' => 'Ada di ruang direksi dan Sekar Jagad',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:25:57',
                'updated_at' => '2026-04-08 08:25:57',
            ],
            [
                'id' => 11,
                'code' => 'ACC-FT',
                'name' => 'Foto-Foto',
                'description' => 'Foto departemen dan foto direksi',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:01',
                'updated_at' => '2026-04-08 08:26:01',
            ],
            [
                'id' => 12,
                'code' => 'TLKM-TL',
                'name' => 'Telepon',
                'description' => 'Merk Panasonic',
                'is_consumable' => false,
                'category_id' => 13,
                'created_at' => '2026-04-08 08:26:06',
                'updated_at' => '2026-04-08 08:26:06',
            ],
            [
                'id' => 13,
                'code' => 'ACC-JAM',
                'name' => 'Jam Dinding',
                'description' => 'Merk Seiko',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:11',
                'updated_at' => '2026-04-08 08:26:11',
            ],
            [
                'id' => 14,
                'code' => 'ACC-GL',
                'name' => 'Glassboard',
                'description' => 'Di ruang para Kadep dan PM',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:18',
                'updated_at' => '2026-04-08 08:26:18',
            ],
            [
                'id' => 15,
                'code' => 'ACC-POT',
                'name' => 'Pot Tanaman',
                'description' => 'Berbagai model dan bentuk',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:30',
                'updated_at' => '2026-04-08 08:26:30',
            ],
            [
                'id' => 16,
                'code' => 'ACC-TS',
                'name' => 'Tempat Sampah',
                'description' => 'Setiap ruangan',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:36',
                'updated_at' => '2026-04-08 08:26:36',
            ],
            [
                'id' => 17,
                'code' => 'ACC-LS',
                'name' => 'Lukisan',
                'description' => 'Setiap ruangan',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:40',
                'updated_at' => '2026-04-08 08:26:40',
            ],
            [
                'id' => 18,
                'code' => 'ACC-PH',
                'name' => 'Pengharum Ruangan',
                'description' => 'Merk Glant',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:46',
                'updated_at' => '2026-04-08 08:26:46',
            ],
            [
                'id' => 19,
                'code' => 'ACC-P3K',
                'name' => 'Kotak P3k',
                'description' => 'Kotak',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:51',
                'updated_at' => '2026-04-08 08:26:51',
            ],
            [
                'id' => 20,
                'code' => 'ACC-TK',
                'name' => 'Troli Kecil',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:26:56',
                'updated_at' => '2026-04-08 08:26:56',
            ],
            [
                'id' => 21,
                'code' => 'ACC-GE',
                'name' => 'Gerobak Etalase',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:02',
                'updated_at' => '2026-04-08 08:27:02',
            ],
            [
                'id' => 22,
                'code' => 'ACC-BT',
                'name' => 'Braket Tv Standing',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2025-11-18 11:44:07',
                'updated_at' => '2025-11-18 11:44:07',
            ],
            [
                'id' => 23,
                'code' => 'ACC-CM',
                'name' => 'Convex Miror',
                'description' => 'Cermin cembung 45cm',
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:08',
                'updated_at' => '2026-04-08 08:27:08',
            ],
            [
                'id' => 24,
                'code' => 'ACC-LAY',
                'name' => 'Layar',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:13',
                'updated_at' => '2026-04-08 08:27:13',
            ],
            [
                'id' => 25,
                'code' => 'ACC-RP',
                'name' => 'Rak Piring',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:18',
                'updated_at' => '2026-04-08 08:27:18',
            ],
            [
                'id' => 26,
                'code' => 'ACC-KA',
                'name' => 'Kipas Angin',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:23',
                'updated_at' => '2026-04-08 08:27:23',
            ],
            [
                'id' => 27,
                'code' => 'ACC-RS',
                'name' => 'Rak Sepatu',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:28',
                'updated_at' => '2026-04-08 08:27:28',
            ],
            [
                'id' => 28,
                'code' => 'ACC-TB',
                'name' => 'Troli Besar',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:32',
                'updated_at' => '2026-04-08 08:27:32',
            ],
            [
                'id' => 29,
                'code' => 'ACC-PK',
                'name' => 'Pot Kecil',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:43',
                'updated_at' => '2026-04-08 08:27:43',
            ],
            [
                'id' => 30,
                'code' => 'ACC-TM',
                'name' => 'Tenis Meja',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:47',
                'updated_at' => '2026-04-08 08:27:47',
            ],
            [
                'id' => 31,
                'code' => 'ACC-TAP',
                'name' => 'Termos Air Panas',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:53',
                'updated_at' => '2026-04-08 08:27:53',
            ],
            [
                'id' => 32,
                'code' => 'ACC-DP',
                'name' => 'Dispenser',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:27:58',
                'updated_at' => '2026-04-08 08:27:58',
            ],
            [
                'id' => 33,
                'code' => 'ACC-KL',
                'name' => 'Karpet Lantai',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:28:03',
                'updated_at' => '2026-04-08 08:28:03',
            ],
            [
                'id' => 34,
                'code' => 'ACC-BRS',
                'name' => 'Brangkas',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:28:08',
                'updated_at' => '2026-04-08 08:28:08',
            ],
            [
                'id' => 35,
                'code' => 'ACC-TO',
                'name' => 'Tabung Oksigen',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:28:14',
                'updated_at' => '2026-04-08 08:28:14',
            ],
            [
                'id' => 36,
                'code' => 'ACC-STB',
                'name' => 'Storage Tool Box',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:28:25',
                'updated_at' => '2026-04-08 08:28:25',
            ],
            [
                'id' => 37,
                'code' => 'ACC-PC',
                'name' => 'Paper Cutter',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:28:37',
                'updated_at' => '2026-04-08 08:28:37',
            ],
            [
                'id' => 38,
                'code' => 'ACC-PS',
                'name' => 'Paper Shredder',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2025-05-26 14:30:47',
                'updated_at' => '2025-05-26 14:30:47',
            ],
            [
                'id' => 39,
                'code' => 'ACC-BL',
                'name' => 'Bor Listrik',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:06',
                'updated_at' => '2026-04-08 08:29:06',
            ],
            [
                'id' => 40,
                'code' => 'ACC-GR',
                'name' => 'Gerinda',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:11',
                'updated_at' => '2026-04-08 08:29:11',
            ],
            [
                'id' => 41,
                'code' => 'ACC-RB',
                'name' => 'Rak Brosur',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:16',
                'updated_at' => '2026-04-08 08:29:16',
            ],
            [
                'id' => 42,
                'code' => 'ACC-TI',
                'name' => 'Kotak Tissue',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:22',
                'updated_at' => '2026-04-08 08:29:22',
            ],
            [
                'id' => 43,
                'code' => 'ACC-KR',
                'name' => 'Koper',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:27',
                'updated_at' => '2026-04-08 08:29:27',
            ],
            [
                'id' => 44,
                'code' => 'ACC-FC',
                'name' => 'Flipchart',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:32',
                'updated_at' => '2026-04-08 08:29:32',
            ],
            [
                'id' => 45,
                'code' => 'ACC-AM',
                'name' => 'Alat Musik',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:38',
                'updated_at' => '2026-04-08 08:29:38',
            ],
            [
                'id' => 46,
                'code' => 'ACC-PD',
                'name' => 'Podium',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-08 08:29:43',
                'updated_at' => '2026-04-08 08:29:43',
            ],
            [
                'id' => 47,
                'code' => 'ACC-GPS',
                'name' => 'GPS',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-04-13 14:39:10',
                'updated_at' => '2026-04-13 14:39:10',
            ],
            [
                'id' => 48,
                'code' => 'ACC-DG',
                'name' => 'Tensimeter Digital',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-07-23 14:42:26',
                'updated_at' => '2026-07-23 14:42:26',
            ],
            [
                'id' => 49,
                'code' => 'ACC-PM',
                'name' => 'Perlengkapan Motor',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 2,
                'created_at' => '2026-07-29 13:58:13',
                'updated_at' => '2026-07-29 13:58:13',
            ],
            [
                'id' => 50,
                'code' => 'COMP-DESK',
                'name' => 'Desktop',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 3,
                'created_at' => '2026-04-08 08:29:48',
                'updated_at' => '2026-04-08 08:29:48',
            ],
            [
                'id' => 51,
                'code' => 'COMP-NB',
                'name' => 'Notebook',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 3,
                'created_at' => '2026-04-08 08:30:07',
                'updated_at' => '2026-04-08 08:30:07',
            ],
            [
                'id' => 52,
                'code' => 'COMP-SVR',
                'name' => 'Server',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 3,
                'created_at' => '2026-04-08 08:30:16',
                'updated_at' => '2026-04-08 08:30:16',
            ],
            [
                'id' => 53,
                'code' => 'COMP-WORK',
                'name' => 'Workstation',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 3,
                'created_at' => '2026-04-08 08:30:20',
                'updated_at' => '2026-04-08 08:30:20',
            ],
            [
                'id' => 54,
                'code' => 'MON-CRT',
                'name' => 'Tabung',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 4,
                'created_at' => '2026-04-08 08:32:21',
                'updated_at' => '2026-04-08 08:32:21',
            ],
            [
                'id' => 55,
                'code' => 'MON-LCD',
                'name' => 'LCD',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 4,
                'created_at' => '2026-04-08 08:32:26',
                'updated_at' => '2026-04-08 08:32:26',
            ],
            [
                'id' => 56,
                'code' => 'PERP-ACCS',
                'name' => 'Accesoris',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2026-04-08 08:32:51',
                'updated_at' => '2026-04-08 08:32:51',
            ],
            [
                'id' => 57,
                'code' => 'PERP-NETW',
                'name' => 'Network',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2026-04-08 08:32:56',
                'updated_at' => '2026-04-08 08:32:56',
            ],
            [
                'id' => 58,
                'code' => 'PERP-COMM',
                'name' => 'Communication',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2026-04-08 08:33:00',
                'updated_at' => '2026-04-08 08:33:00',
            ],
            [
                'id' => 59,
                'code' => 'PERP-MMD',
                'name' => 'Multimedia',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2026-04-08 08:33:05',
                'updated_at' => '2026-04-08 08:33:05',
            ],
            [
                'id' => 60,
                'code' => 'PERP-CAM',
                'name' => 'Camera',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2026-04-08 08:33:13',
                'updated_at' => '2026-04-08 08:33:13',
            ],
            [
                'id' => 61,
                'code' => 'PERP-ACCN',
                'name' => 'Access Control',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2026-04-08 08:33:17',
                'updated_at' => '2026-04-08 08:33:17',
            ],
            [
                'id' => 62,
                'code' => 'PERP-MEXT',
                'name' => 'Media External',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2026-04-08 08:33:26',
                'updated_at' => '2026-04-08 08:33:26',
            ],
            [
                'id' => 63,
                'code' => 'PERP-PROJ',
                'name' => 'Projector',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2016-12-19 13:42:52',
                'updated_at' => '2016-12-19 13:42:52',
            ],
            [
                'id' => 64,
                'code' => 'PERP-RAKS',
                'name' => 'Rak Server',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2016-12-19 13:44:06',
                'updated_at' => '2016-12-19 13:44:06',
            ],
            [
                'id' => 65,
                'code' => 'PERP-SCAN',
                'name' => 'Scanner',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2016-12-19 13:44:37',
                'updated_at' => '2016-12-19 13:44:37',
            ],
            [
                'id' => 66,
                'code' => 'PERP-SCRN',
                'name' => 'Screen Presentation',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2016-12-19 13:45:21',
                'updated_at' => '2016-12-19 13:45:21',
            ],
            [
                'id' => 67,
                'code' => 'PERP-UPS',
                'name' => 'UPS',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2016-12-19 13:46:35',
                'updated_at' => '2016-12-19 13:46:35',
            ],
            [
                'id' => 68,
                'code' => 'PERP-VGA',
                'name' => 'VGA',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2016-12-19 13:46:48',
                'updated_at' => '2016-12-19 13:46:48',
            ],
            [
                'id' => 69,
                'code' => 'PERP-STRG',
                'name' => 'Storage',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 5,
                'created_at' => '2022-12-09 10:24:05',
                'updated_at' => '2022-12-09 10:24:05',
            ],
            [
                'id' => 70,
                'code' => 'PRNT-INK',
                'name' => 'Inkjet',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 6,
                'created_at' => '2016-12-19 08:55:42',
                'updated_at' => '2016-12-19 08:55:42',
            ],
            [
                'id' => 71,
                'code' => 'PRNT-LJT',
                'name' => 'Laserjet',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 6,
                'created_at' => '2016-12-19 09:12:28',
                'updated_at' => '2016-12-19 09:12:28',
            ],
            [
                'id' => 72,
                'code' => 'PRNT-DOT',
                'name' => 'Dotmatrik',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 6,
                'created_at' => '2016-12-19 09:16:01',
                'updated_at' => '2016-12-19 09:16:01',
            ],
            [
                'id' => 73,
                'code' => 'PRNT-PLT',
                'name' => 'Plotter',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 6,
                'created_at' => '2016-12-19 09:18:28',
                'updated_at' => '2016-12-19 09:18:28',
            ],
            [
                'id' => 74,
                'code' => 'PRNT-MLT',
                'name' => 'Multifunction',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 6,
                'created_at' => '2016-12-19 09:32:30',
                'updated_at' => '2016-12-19 09:32:30',
            ],
            [
                'id' => 75,
                'code' => 'PRNT-IDC',
                'name' => 'Id Card',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 6,
                'created_at' => '2016-12-19 09:33:46',
                'updated_at' => '2016-12-19 09:33:46',
            ],
            [
                'id' => 76,
                'code' => 'SOFT-ENG',
                'name' => 'Engineering Software',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 7,
                'created_at' => '2016-12-19 13:49:37',
                'updated_at' => '2016-12-19 13:49:37',
            ],
            [
                'id' => 77,
                'code' => 'SOFT-GEN',
                'name' => 'General Software',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 7,
                'created_at' => '2016-12-19 13:50:06',
                'updated_at' => '2016-12-19 13:50:06',
            ],
            [
                'id' => 78,
                'code' => 'PROP-PRO',
                'name' => 'Property',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 8,
                'created_at' => '2023-06-15 09:34:11',
                'updated_at' => '2023-06-15 09:34:11',
            ],
            [
                'id' => 79,
                'code' => 'MES-WTH',
                'name' => 'Water Heater',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 9,
                'created_at' => '2026-04-08 08:27:38',
                'updated_at' => '2026-04-08 08:27:38',
            ],
            [
                'id' => 80,
                'code' => 'MES-GEN',
                'name' => 'Genset',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 9,
                'created_at' => '2025-02-07 08:57:11',
                'updated_at' => '2025-02-07 08:57:11',
            ],
            [
                'id' => 81,
                'code' => 'MES-PAN',
                'name' => 'Panel',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 9,
                'created_at' => '2025-02-07 08:56:34',
                'updated_at' => '2025-02-07 08:56:34',
            ],
            [
                'id' => 82,
                'code' => 'MES-RP',
                'name' => 'Rumah Pompa',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 9,
                'created_at' => '2025-02-07 08:56:47',
                'updated_at' => '2025-02-07 08:56:47',
            ],
            [
                'id' => 83,
                'code' => 'MES-LIF',
                'name' => 'Lift',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 9,
                'created_at' => '2025-02-07 08:57:02',
                'updated_at' => '2025-02-07 08:57:02',
            ],
            [
                'id' => 84,
                'code' => 'KEND-MO',
                'name' => 'Mobil',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 10,
                'created_at' => '2026-02-10 14:14:52',
                'updated_at' => '2026-02-10 14:14:52',
            ],
            [
                'id' => 85,
                'code' => 'ELEK-CS',
                'name' => 'Ceiling Speaker',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:47:48',
                'updated_at' => '2025-02-06 10:47:48',
            ],
            [
                'id' => 86,
                'code' => 'ELEK-TV',
                'name' => 'TV',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:48:04',
                'updated_at' => '2025-02-06 10:48:04',
            ],
            [
                'id' => 87,
                'code' => 'ELEK-SPE',
                'name' => 'Speaker',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:45:05',
                'updated_at' => '2025-02-06 10:45:05',
            ],
            [
                'id' => 88,
                'code' => 'ELEK-MPK',
                'name' => 'Mesin Penghancur Kopi',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:45:20',
                'updated_at' => '2025-02-06 10:45:20',
            ],
            [
                'id' => 89,
                'code' => 'ELEK-MK',
                'name' => 'Mesin Kopi',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:45:31',
                'updated_at' => '2025-02-06 10:45:31',
            ],
            [
                'id' => 90,
                'code' => 'ELEK-HD',
                'name' => 'Heat Detector',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-11-17 09:17:45',
                'updated_at' => '2025-11-17 09:17:45',
            ],
            [
                'id' => 91,
                'code' => 'ELEK-KUL',
                'name' => 'Kulkas',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2024-08-19 13:12:36',
                'updated_at' => '2024-08-19 13:12:36',
            ],
            [
                'id' => 92,
                'code' => 'ELEK-FVC',
                'name' => 'Fogging Volume Control',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-05 11:04:00',
                'updated_at' => '2025-02-05 11:04:00',
            ],
            [
                'id' => 93,
                'code' => 'ELEK-FCT',
                'name' => 'Fogging Control Toa',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-05 11:05:46',
                'updated_at' => '2025-02-05 11:05:46',
            ],
            [
                'id' => 94,
                'code' => 'ELEK-CCT',
                'name' => 'CCTV',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:46:37',
                'updated_at' => '2025-02-06 10:46:37',
            ],
            [
                'id' => 95,
                'code' => 'ELEK-SPR',
                'name' => 'Sprinkler',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:46:48',
                'updated_at' => '2025-02-06 10:46:48',
            ],
            [
                'id' => 96,
                'code' => 'ELEK-FR',
                'name' => 'Fingerprint Reader',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:46:06',
                'updated_at' => '2025-02-06 10:46:06',
            ],
            [
                'id' => 97,
                'code' => 'ELEK-SD',
                'name' => 'Smoke Detector',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-02-06 10:47:17',
                'updated_at' => '2025-02-06 10:47:17',
            ],
            [
                'id' => 98,
                'code' => 'ELEK-ATS',
                'name' => 'Alat Tester',
                'description' => 'Alat proyek',
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-09-09 10:56:51',
                'updated_at' => '2025-09-09 10:56:51',
            ],
            [
                'id' => 99,
                'code' => 'ELEK-MIC',
                'name' => 'Microwave',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-11-18 11:42:26',
                'updated_at' => '2025-11-18 11:42:26',
            ],
            [
                'id' => 100,
                'code' => 'ELEK-CP',
                'name' => 'Camera Pocket',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2025-12-10 17:25:22',
                'updated_at' => '2025-12-10 17:25:22',
            ],
            [
                'id' => 101,
                'code' => 'ELEK-TG',
                'name' => 'Topografi',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2026-03-12 09:40:51',
                'updated_at' => '2026-03-12 09:40:51',
            ],
            [
                'id' => 102,
                'code' => 'ELEK-MD',
                'name' => 'Multigas Detector',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2026-03-12 09:46:25',
                'updated_at' => '2026-03-12 09:46:25',
            ],
            [
                'id' => 103,
                'code' => 'PDGR-ACSP',
                'name' => 'AC Split',
                'description' => 'Merk LG, Sharp dan Daikin',
                'is_consumable' => false,
                'category_id' => 12,
                'created_at' => '2025-01-30 10:09:39',
                'updated_at' => '2025-01-30 10:09:39',
            ],
            [
                'id' => 104,
                'code' => 'PDGR-AHU',
                'name' => 'AC AHU',
                'description' => 'AC conditioner',
                'is_consumable' => false,
                'category_id' => 12,
                'created_at' => '2025-01-30 10:07:25',
                'updated_at' => '2025-01-30 10:07:25',
            ],
            [
                'id' => 105,
                'code' => 'PDGR-ACS',
                'name' => 'AC Standing',
                'description' => 'Di ruang Sekar Jagad dan Tiga Negeri',
                'is_consumable' => false,
                'category_id' => 12,
                'created_at' => '2025-01-30 10:07:44',
                'updated_at' => '2025-01-30 10:07:44',
            ],
            [
                'id' => 106,
                'code' => 'PDGR-ACN',
                'name' => 'AC Central',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 12,
                'created_at' => '2025-01-30 10:08:13',
                'updated_at' => '2025-01-30 10:08:13',
            ],
            [
                'id' => 107,
                'code' => 'PDGR-ACP',
                'name' => 'AC Portable',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 12,
                'created_at' => '2025-02-05 13:39:44',
                'updated_at' => '2025-02-05 13:39:44',
            ],
            [
                'id' => 108,
                'code' => 'TLKM-FAX',
                'name' => 'Fax',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 13,
                'created_at' => '2026-04-08 08:33:09',
                'updated_at' => '2026-04-08 08:33:09',
            ],
            [
                'id' => 109,
                'code' => 'TLKM-HT',
                'name' => 'HT',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 13,
                'created_at' => '2025-02-06 10:47:01',
                'updated_at' => '2025-02-06 10:47:01',
            ],
            [
                'id' => 110,
                'code' => 'TLKM-SP',
                'name' => 'Smartphone',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 13,
                'created_at' => '2025-03-19 09:59:17',
                'updated_at' => '2025-03-19 09:59:17',
            ],
            [
                'id' => 111,
                'code' => 'ELEK-EXH',
                'name' => 'Exhaust',
                'description' => null,
                'is_consumable' => false,
                'category_id' => 11,
                'created_at' => '2026-10-07 09:00:00',
                'updated_at' => '2026-10-07 09:00:00',
            ],
        ];

        $isSqlsrv = DB::connection()->getDriverName() === 'sqlsrv';

        if ($isSqlsrv) {
            DB::unprepared('SET IDENTITY_INSERT subcategories ON;');
        }

        foreach (array_chunk($records, 100) as $chunk) {
            DB::table('subcategories')->upsert(
                $chunk,
                ['id'],
                ['code', 'name', 'description', 'is_consumable', 'category_id', 'updated_at']
            );
        }

        if ($isSqlsrv) {
            DB::unprepared('SET IDENTITY_INSERT subcategories OFF;');
        }
    }
}
