<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActualVendorSeeder extends Seeder
{
    /**
     * Run the master Vendor database seeds.
     * Total records: 111
     */
    public function run(): void
    {
        $records = [
            [
                'id' => 1,
                'code' => 'VN00001',
                'name' => 'Koperasi RE',
                'address' => 'Jl. Kalibata Timur 1 No. 27',
                'phone_number' => '(021) 79181180',
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => '02179181180',
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-04-05 14:10:42',
                'updated_at' => '2018-04-05 14:10:42',
            ],
            [
                'id' => 2,
                'code' => 'VN00002',
                'name' => 'Alfa Solusi',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:20:41',
                'updated_at' => '2017-01-04 13:20:41',
            ],
            [
                'id' => 3,
                'code' => 'VN00003',
                'name' => 'Cahaya Sukses',
                'address' => 'Komplek Rukan Puri Mutiara, Blok A No. 99, Sunter, RT. 2 / RW. 5, Sunter Agung, Tj. Priok, Kota Jakarta Utara, Daerah Khusus Ibukota Jakarta 14350',
                'phone_number' => '021-5601496',
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-10-25 13:18:51',
                'updated_at' => '2018-10-25 13:18:51',
            ],
            [
                'id' => 4,
                'code' => 'VN00004',
                'name' => 'Cascasia',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:26:50',
                'updated_at' => '2017-01-04 13:26:50',
            ],
            [
                'id' => 5,
                'code' => 'VN00008',
                'name' => 'Daniel',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:28:55',
                'updated_at' => '2017-01-04 13:28:55',
            ],
            [
                'id' => 6,
                'code' => 'VN00009',
                'name' => 'EDPMEDIA',
                'address' => null,
                'phone_number' => '021-5805828 / 29',
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:30:10',
                'updated_at' => '2017-01-04 13:30:10',
            ],
            [
                'id' => 7,
                'code' => 'VN00010',
                'name' => 'Everest Technology',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:30:28',
                'updated_at' => '2017-01-04 13:30:28',
            ],
            [
                'id' => 8,
                'code' => 'VN00011',
                'name' => 'Glodok',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:30:37',
                'updated_at' => '2017-01-04 13:30:37',
            ],
            [
                'id' => 9,
                'code' => 'VN00012',
                'name' => 'Gramedia',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:30:49',
                'updated_at' => '2017-01-04 13:30:49',
            ],
            [
                'id' => 10,
                'code' => 'VN00013',
                'name' => 'Indosystem',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:30:58',
                'updated_at' => '2017-01-04 13:30:58',
            ],
            [
                'id' => 11,
                'code' => 'VN00015',
                'name' => 'Multimedia Sejahtera Servitama',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:31:19',
                'updated_at' => '2017-01-04 13:31:19',
            ],
            [
                'id' => 12,
                'code' => 'VN00016',
                'name' => 'Optima Solusindo Informatika',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:31:33',
                'updated_at' => '2017-01-04 13:31:33',
            ],
            [
                'id' => 13,
                'code' => 'VN00017',
                'name' => 'Panca Putra',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:31:50',
                'updated_at' => '2017-01-04 13:31:50',
            ],
            [
                'id' => 14,
                'code' => 'VN00019',
                'name' => 'Sarana Aircon Utama',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:32:21',
                'updated_at' => '2017-01-04 13:32:21',
            ],
            [
                'id' => 15,
                'code' => 'VN00021',
                'name' => 'Sentra Grafika Kompumedia',
                'address' => 'Jl. Kaliata Timur II No 27 PT Rekayasa Engineering Gedung Graha RE Lt. Mezzanine Div ICT',
                'phone_number' => '81310527999',
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-11-12 08:31:08',
                'updated_at' => '2018-11-12 08:31:08',
            ],
            [
                'id' => 16,
                'code' => 'VN00022',
                'name' => 'Siemens',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:33:47',
                'updated_at' => '2017-01-04 13:33:47',
            ],
            [
                'id' => 17,
                'code' => 'VN00023',
                'name' => 'Sinergi',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:33:56',
                'updated_at' => '2017-01-04 13:33:56',
            ],
            [
                'id' => 18,
                'code' => 'VN00024',
                'name' => 'Surabaya',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2017-01-04 13:34:10',
                'updated_at' => '2017-01-04 13:34:10',
            ],
            [
                'id' => 19,
                'code' => 'VN00025',
                'name' => 'Wilerdtindo',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 10:37:36',
                'updated_at' => '2018-03-23 10:37:36',
            ],
            [
                'id' => 20,
                'code' => 'VN00026',
                'name' => 'PT Paradise Perkasa',
                'address' => 'Jl. Perancis No. L78 Kosambi, Dadap, Tangerang - Banten 15213',
                'phone_number' => '62 21 2967 3939',
                'email' => 'info@paradiseperkasa.com',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => 'manroe@paradiseperkasa.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 10:37:36',
                'updated_at' => '2018-03-23 10:37:36',
            ],
            [
                'id' => 21,
                'code' => 'VN00027',
                'name' => 'PT Loka Manggala',
                'address' => 'Mutiara Taman Palem Blok A. 8 No. 8 - Cengkareng Timur - Jakarta 11730',
                'phone_number' => '62 21 5435 0011',
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 22,
                'code' => 'VN00028',
                'name' => 'PT Golden Pratama Engineering',
                'address' => 'Jl. Boulevard Raya BA 2/56 Gading Serpong, Pakulonan Barat, Tangerang, Banten 15810',
                'phone_number' => '62 21 5420 2980',
                'email' => 'sales@ptgoldenpe.com',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 23,
                'code' => 'VN00029',
                'name' => 'PT Crane Indonesia',
                'address' => 'Kawasan Industri Delta Silicone Blok Ae No. 49, Jl. Akasia, Lippo Cikarang, Bekasi',
                'phone_number' => '62 21 8990 7980',
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 24,
                'code' => 'VN00030',
                'name' => 'PT Mitra Galperti',
                'address' => 'Sovereign Plaza, 6th Floor Jl. TB Simatupang Kav. 36 Cilandak, Jakarta Selatan 12430',
                'phone_number' => '62 21 2940 0108',
                'email' => 'sales@galperti.co.id',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 25,
                'code' => 'VN00031',
                'name' => 'PT Fajar Benua Indopack',
                'address' => 'Jl. Mayor Oking Jayaatmaja No. 88 Cibinong 16911 Jawa Barat, Indonesia',
                'phone_number' => '62 21 8791 8838',
                'email' => 'sales@fajarbenua.co.id',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 26,
                'code' => 'VN00032',
                'name' => 'PT Nichias Sunijaya',
                'address' => 'Panin Life Center 2nd Floor Room 205 Jl. Letjend. S. Parman Kav. 91 Jakarta 11420',
                'phone_number' => '62 21 5695 6207',
                'email' => 'industrial_admin@nichias-id.com',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => 'autoparts@nichias-id.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 27,
                'code' => 'VN00033',
                'name' => 'PT Gamako Ekakarsa',
                'address' => 'Jl. Pinangsia Timur No. 44 Jakarta 11110',
                'phone_number' => '62 21 6902 756',
                'email' => 'sales@gamako.co.id',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => 'donny@gamako.co.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 28,
                'code' => 'VN00034',
                'name' => 'PT Binder Indonesia',
                'address' => 'Jl. Pangeran Diponegoro No. 108 - Tambun Bekasi 17510',
                'phone_number' => '62 21 8822 150',
                'email' => 'sales@binderindo.co.id',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 29,
                'code' => 'VN00035',
                'name' => 'PT Kranindo Prima',
                'address' => 'Jl. Pangeran Jayakarta 46. Blok A1. Jakarta 10730',
                'phone_number' => '62 21 6243 151',
                'email' => 'suherman@kranindoprima.com',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => 'suherman@kranindoprima.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 30,
                'code' => 'VN00036',
                'name' => 'PT Karya Prima Suplindo',
                'address' => 'Komplek Griya Inti Sentosa, Ruko Sunter Icon, Jl. Griya Sejahtera Blok L - 1 No. 12 - 14, Jakarta Utara 14350',
                'phone_number' => '62 21 2946 0111',
                'email' => 'sales@karyaprimasuplindo.co.id',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 31,
                'code' => 'VN00037',
                'name' => 'PT KPM Oil & Gas',
                'address' => 'PSW Tower, 8th Floor, Jl. Pangeran Antasari No. 75, Cilandak, Jakarta Selatan, 12430',
                'phone_number' => '62 21 3970 8090',
                'email' => null,
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 32,
                'code' => 'VN00038',
                'name' => 'PT Valvindo Megah',
                'address' => 'Jl. Pangeran Jayakarta 68 Blok B No. 23 Jakarta',
                'phone_number' => '62 21 6498 323',
                'email' => 'sales@valvindo.com',
                'description' => null,
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 33,
                'code' => 'VN00039',
                'name' => 'PT Fors Fortid Indonesia',
                'address' => 'L\'Avenue Office Tower 18th Floor Jl. Raya Pasar Minggu Kav. 16, Pancoran Jakarta Selatan 12780',
                'phone_number' => '021-8066 7133',
                'email' => 'marketing@fors-fortis.com',
                'description' => 'Steel door Bostinco',
                'contact_person_1' => 'Yudianto',
                'cp_email_1' => 'yudi.bostinco@gmail.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 34,
                'code' => 'VN00040',
                'name' => 'PT Bluescope Lysaght Indonesia',
                'address' => 'Jl. Desa Danau Indah Blok Dd2/2 Kawasan Industri MM2100, Cibitung, Bekasi, Indonesia',
                'phone_number' => '021-8998 2965',
                'email' => null,
                'description' => 'Roofing',
                'contact_person_1' => 'Dicky Prabowo',
                'cp_email_1' => 'dicky.prabowo@bluescope.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 35,
                'code' => 'VN00041',
                'name' => 'PT Union Metal',
                'address' => 'Menara Sudirman 16th Floor Jl. Jend. Sudirman Kav. 60',
                'phone_number' => '021-522 7707',
                'email' => 'marketing@unionmetal.co.id',
                'description' => 'Floordeck',
                'contact_person_1' => 'Anton',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 36,
                'code' => 'VN00042',
                'name' => 'Indonesian Epoxy Floor',
                'address' => null,
                'phone_number' => null,
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Andriyana, SE',
                'cp_email_1' => 'marketingepoxy@gmail.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 37,
                'code' => 'VN00043',
                'name' => 'PT Karlita Emas',
                'address' => 'Jl. Pegangsaan Dua Rukan Royal Gading Square Blok RG. 10/9 Jakarta Utara 14250',
                'phone_number' => '021-4483 4970 / 1671 / 1540',
                'email' => 'info@karlitaemas.com',
                'description' => 'Steel grating',
                'contact_person_1' => 'Ulva W',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 38,
                'code' => 'VN00044',
                'name' => 'Adimix PCI Indonesia',
                'address' => 'Jl. Imam Bonjol, Desa Telaga Asih, Cibitung, Bekasi',
                'phone_number' => '021-88362536',
                'email' => null,
                'description' => 'Spun pile',
                'contact_person_1' => 'Rinintia Arimurti',
                'cp_email_1' => 'rin.arimurti@gmail.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 39,
                'code' => 'VN00045',
                'name' => 'PT KSB Indonesia & PT KSB Sales Indonesia',
                'address' => 'Jl. Timor Block D2 - 1, MM2100 Industrial Town Cibitung, 17520 Indonesia, Secure Building Block B, 3 Floor, Jl. Raya Protokol Halim Perdanakusuma, Jakarta 13610 Indonesia',
                'phone_number' => '+62 21 808 86509',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Tegar Supriyadi',
                'cp_email_1' => 'tegar.supriyadi@ksb.co.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 40,
                'code' => 'VN00046',
                'name' => 'PT Petrotec Guna Perkasa',
                'address' => 'Head Office: Jl. Raya Pos Pengumben No. 21H - Jakarta Barat 11630 - Indonesia, Operational Office: Jl. Tekno 4 Blok G1 No. 28 - 29, Taman Tekno - BSD City, Tangerang 15314 - Indonesia',
                'phone_number' => '+62-21-585 9764',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Christy',
                'cp_email_1' => 'christy@pgp.co.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 41,
                'code' => 'VN00047',
                'name' => 'PT Ashcrofindo Manunggal',
                'address' => 'Jl. Pluit Selatan I No. 59, RT. 21 / RW. 8, Pluit, Penjaringan, Kota Jakarta Utara, Daerah Khusus Ibukota Jakarta 14450',
                'phone_number' => '+62-21-66 11 55 7',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Rizal',
                'cp_email_1' => 'rizal@ashcrofindo.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 42,
                'code' => 'VN00048',
                'name' => 'PT Bumi Cahaya Unggul',
                'address' => 'Jl. Rawa Kepiting No. 3, Kawasan Industri Pulo Gadung, Rw. 3, Rawa Terate, Jakarta, Rw. 3, RW. Terate, Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13920',
                'phone_number' => '+62-21-29558400',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Muluk',
                'cp_email_1' => 'muluk.a@bcupt.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 43,
                'code' => 'VN00049',
                'name' => 'PT Roda Nurmala',
                'address' => 'PT Roda Nurmala Komplek Perkantoran Royal Sunter Jl. Danau Sunter Selatan Blok F No. 16 - 17 Jakarta Utara 14350 Indonesia',
                'phone_number' => '+62 21 6515689',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Adi',
                'cp_email_1' => 'adi@rodanurmala.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 44,
                'code' => 'VN00050',
                'name' => 'PT Duraquipt Cemerlang',
                'address' => 'Jl. Limo Raya No. 9, Limo, Kota Depok, Jawa Barat 16515',
                'phone_number' => '+62 21 7535559',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Neneng',
                'cp_email_1' => 'neneng@ptdqc.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 45,
                'code' => 'VN00051',
                'name' => 'PT Enerflex Indonesia',
                'address' => 'Jl. Raya Cilandak KKO Jl. Cilandak Commercial Estate No. 105, RT. 13 / RW. 5, Cilandak Tim., Pasar Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12560',
                'phone_number' => '+62 21 789 0180',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'R. Chandra',
                'cp_email_1' => 'rchandra@enerflex.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 46,
                'code' => 'VN00052',
                'name' => 'PT SAS International',
                'address' => 'Graha Semesta Building, 4th Floor, Jl. Raya Kebayoran Lama Pal VII. No. 31, Jakarta 12210, Indonesia',
                'phone_number' => '+62-21-5347880',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Dani',
                'cp_email_1' => 'dani@sasinternasional.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 47,
                'code' => 'VN00053',
                'name' => 'PT Fajar Mas Murni',
                'address' => 'Jl. Raya Narogong 214 Bekasi 17116, West Java, Indonesia',
                'phone_number' => '+62-21 820 3989 / +62-21 820 3994',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Cesar',
                'cp_email_1' => 'cesar@fajarmasmurni.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 48,
                'code' => 'VN00054',
                'name' => 'PT Pacific Process Engineering',
                'address' => 'Techno Park Industrial Estate, Sector XI, Block G2, No. 5, Bumi Serpong Damai (BSD) City 15322',
                'phone_number' => '+62 21 7588 1945',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Jabbar',
                'cp_email_1' => 'abdul.jabbar@pacificprocessengineering.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 49,
                'code' => 'VN00055',
                'name' => 'PT Dinar Inti Duba',
                'address' => 'Gedung Hin An Lantai 3A Suite D., Jl. Kh. Hasyim Ashari No. 4 - 6 Jakarta Pusat',
                'phone_number' => '021-22633723',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Steven',
                'cp_email_1' => 'dinarintiduba@gmail.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 50,
                'code' => 'VN00056',
                'name' => 'PT Indobara',
                'address' => 'Head Office: Jl. Gunung Sahari Raya, No. 57 G, Jakarta 10610',
                'phone_number' => '+62-21 420 9908 / +62-21 420 9033',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Jeffry',
                'cp_email_1' => 'jeffry@indobara.co.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 51,
                'code' => 'VN00057',
                'name' => 'PT Rantai Laut',
                'address' => 'Jl. Pintu Air Raya No. 38H, Complex 38, Jakarta Pusat 10710, Indonesia',
                'phone_number' => '+62-21 386-0505 / +62-21 386-0606',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Bobby Heryadi',
                'cp_email_1' => 'bobby@rantai-laut.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 52,
                'code' => 'VN00058',
                'name' => 'PT Sabrindo',
                'address' => 'Komp. Ruko Cempaka Mas Blok J No. 10, Jl. Letjen Suprapto, Jakarta - 10640 Indonesia',
                'phone_number' => '+62-21-29558400',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Gilang',
                'cp_email_1' => "gilang@saberindo.co.id\ninfo@saberindo.co.id",
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 53,
                'code' => 'VN00060',
                'name' => 'PT Kalimutu Mitra Perkasa',
                'address' => 'Sentra Latumeten Blok Aa#18, Jl. Raya Latumenten Kav. 50 - Jakarta 11460',
                'phone_number' => '021 5696 0197',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Citra Paramita',
                'cp_email_1' => 'citra.hparamita@kalimutu.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 54,
                'code' => 'VN00061',
                'name' => 'PT Rejeki Utama',
                'address' => 'Wisma Geha. Jl. Timor No. 25. Jakarta 10350 - Indonesia',
                'phone_number' => '021 3162924',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Susanto Pranoto',
                'cp_email_1' => 'inquiry@rejekiutama.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 55,
                'code' => 'VN00062',
                'name' => 'Trafindo',
                'address' => 'Jl. Hayam Wuruk 4',
                'phone_number' => '021 3451384',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Ir. Irwan Rochandi',
                'cp_email_1' => 'irwan.r@trafoindonesia.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 56,
                'code' => 'VN00063',
                'name' => 'Perpro',
                'address' => 'Jl. Danau Sunter Utara Blok B 36A No. 10',
                'phone_number' => '021 6400751 / 021 6401849',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Ikhsan Fahri Hanafi',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 57,
                'code' => 'VN00064',
                'name' => 'Philips',
                'address' => 'Philips Building 2nd Floor Jl. Buncit Raya Kav. 99 - 100',
                'phone_number' => '021 29651333',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Yopy Handian',
                'cp_email_1' => 'yopy.handian@philips.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 58,
                'code' => 'VN00065',
                'name' => 'Kotaminyak',
                'address' => 'Jl. Bandengan Selatan No. 60A',
                'phone_number' => '021 6621725',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Handri Petrus Sitinjak',
                'cp_email_1' => 'petrus@kotaminyak.co.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 59,
                'code' => 'VN00066',
                'name' => 'Erico',
                'address' => 'Erico Limited, Sampoerna Strategic Square, South Tower B Level 18, Jl. Jend. Sudirman Kav. 45 - 46',
                'phone_number' => '021 5750941',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Erwin Elysar',
                'cp_email_1' => 'eelysar@erico.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 60,
                'code' => 'VN00067',
                'name' => 'Schneider Electric',
                'address' => 'Ventura Building 7th Floor Jl. R.A. Kartini Kav. 26, Cilandak',
                'phone_number' => '021 7504406',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Ir. Nanang Agus Sandjoko',
                'cp_email_1' => 'nanang.agus-sandjoko@schneider-electric.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 61,
                'code' => 'VN00068',
                'name' => 'Socomec',
                'address' => 'Vinilon Building - Unit 02A, 3rd Floor Jl. Raden Saleh Kav. 13 - 17',
                'phone_number' => '021 29619645',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Rana Gemilang',
                'cp_email_1' => 'rana.gemilang@socomec.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 62,
                'code' => 'VN00069',
                'name' => 'Trakindo',
                'address' => 'Gedung TMT 11th - 17th Floor Jl. Cilandak KKO No. 1',
                'phone_number' => '021 29976620 / 021 7822373',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Eko Aditiya',
                'cp_email_1' => 'eko.aditya@trakindo.co.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 63,
                'code' => 'VN00070',
                'name' => 'Berkah Cipta Persada',
                'address' => 'Kawasan Industri Greenland - Kota Deltamas Jl. Greenland IV Blok AC No. 07 Cikarang',
                'phone_number' => '021 89972630',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Yosserizal Adlim',
                'cp_email_1' => 'yosserizal.adlim@berkahcipta.co.id',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 64,
                'code' => 'VN00071',
                'name' => 'Sucaco',
                'address' => 'Jl. Kebon Sirih 71',
                'phone_number' => '021 3100525',
                'email' => null,
                'description' => null,
                'contact_person_1' => 'Agus Ilyas',
                'cp_email_1' => 'agus@sucaco.com',
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2018-03-23 00:00:00',
                'updated_at' => '2018-03-23 00:00:00',
            ],
            [
                'id' => 65,
                'code' => 'VN00072',
                'name' => 'Koperasi Reka Teknika Utama',
                'address' => 'Kalibata Timur 2 No. 27 Jakarta Selatan',
                'phone_number' => '79181180',
                'email' => 'teguh.santoso@re.rekayasa.co.id',
                'description' => 'Melayani semua kebutuhan kantor',
                'contact_person_1' => 'Teguh Santoso',
                'cp_email_1' => null,
                'cp_phone_1' => '081383023481',
                'contact_person_2' => 'Ibu Elsa',
                'cp_email_2' => null,
                'cp_phone_2' => '082122355770',
                'created_at' => '2020-10-01 13:01:41',
                'updated_at' => '2020-10-01 13:01:41',
            ],
            [
                'id' => 66,
                'code' => 'VN00073',
                'name' => 'Kontraktor Rifai',
                'address' => 'Jl. Kalibata Timur 2 No. 27',
                'phone_number' => '0217918180',
                'email' => 'jayadi@gmai.com',
                'description' => 'Pembangunan gedung',
                'contact_person_1' => 'Jaya',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2023-06-15 09:38:20',
                'updated_at' => '2023-06-15 09:38:20',
            ],
            [
                'id' => 67,
                'code' => 'VN00074',
                'name' => 'PT Intisari Komputindo',
                'address' => 'Taman Palem Lestari Blok. H No. 62, Ruko Pelangi - Cengkareng, Jakarta Barat 11730',
                'phone_number' => '02155956262',
                'email' => 'lingga@intisari.co.id',
                'description' => 'Sales',
                'contact_person_1' => 'Lingga',
                'cp_email_1' => null,
                'cp_phone_1' => '085692791484',
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2023-07-07 15:34:41',
                'updated_at' => '2023-07-07 15:34:41',
            ],
            [
                'id' => 68,
                'code' => 'VN00075',
                'name' => 'Yolori',
                'address' => 'Online Tokopedia',
                'phone_number' => '1234567',
                'email' => 'tokopedia@gmail.com',
                'description' => 'Jual periperal komputer',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2023-10-27 14:36:01',
                'updated_at' => '2023-10-27 14:36:01',
            ],
            [
                'id' => 69,
                'code' => 'VN00076',
                'name' => 'Protech Computer',
                'address' => 'Tokopedia Online',
                'phone_number' => '1234567',
                'email' => 'tokopedia@gmail.com',
                'description' => 'Jual PC & laptop',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2023-10-27 14:37:30',
                'updated_at' => '2023-10-27 14:37:30',
            ],
            [
                'id' => 70,
                'code' => 'VN00077',
                'name' => 'Trinity Official Store',
                'address' => 'Tokopedia Online',
                'phone_number' => '1234567',
                'email' => 'it.ops@re.rekayasa.co.id',
                'description' => 'Jual sparepart IT',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-01-21 23:28:06',
                'updated_at' => '2024-01-21 23:28:06',
            ],
            [
                'id' => 71,
                'code' => 'VN00078',
                'name' => 'Agres ID',
                'address' => 'Tokopedia Online',
                'phone_number' => '1234567',
                'email' => 'it.ops@re.rekayasa.co.id',
                'description' => 'Jual laptop',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-01-21 23:29:52',
                'updated_at' => '2024-01-21 23:29:52',
            ],
            [
                'id' => 72,
                'code' => 'VN00079',
                'name' => 'Trans Survey',
                'address' => 'Kembangan Jakarta Barat',
                'phone_number' => '08192120879',
                'email' => 'transsurvey@gmai.com',
                'description' => 'Jakarta barat',
                'contact_person_1' => 'Asep Mulyana',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-01 15:02:53',
                'updated_at' => '2024-02-01 15:02:53',
            ],
            [
                'id' => 73,
                'code' => 'VN00080',
                'name' => 'PT Danan Wingus Sakti',
                'address' => 'Ruko Season City SH/D/07, Jl. Prof Dr. Latumenten No. 33 Blok D Jembatan Besi, Tambora, Jakarta Barat 11320',
                'phone_number' => '02129071330',
                'email' => 'sales@ptdws.co.id',
                'description' => 'Licensed software',
                'contact_person_1' => 'A. Wira W',
                'cp_email_1' => null,
                'cp_phone_1' => '02129071330',
                'contact_person_2' => null,
                'cp_email_2' => 'sales@ptdws.co.id',
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:12:07',
                'updated_at' => '2024-02-13 13:12:07',
            ],
            [
                'id' => 74,
                'code' => 'VN00081',
                'name' => 'PT Multi Prima Mandiri Sukses',
                'address' => 'Jl. Hidup Baru Blok D No. 06 Gunung Sahari, Pademangan, Jakarta Utara 14420',
                'phone_number' => '02199634125',
                'email' => 'sales@multiprint.co.id',
                'description' => 'Service printer, toner & tinta',
                'contact_person_1' => 'Mr. Isman',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:14:37',
                'updated_at' => '2024-02-13 13:14:37',
            ],
            [
                'id' => 75,
                'code' => 'VN00082',
                'name' => 'PT Putraduta Buanasentosa (Indoarsip)',
                'address' => 'Komp. Perkantoran Buncit Mas B - 12, Jl. Mampang Prapatan Raya No. 108 Jakarta Selatan',
                'phone_number' => '0217946390',
                'email' => 'krw-fax@indoarsip.co.id',
                'description' => 'Pengarsipan dokumen',
                'contact_person_1' => 'Mr. Albert',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:17:28',
                'updated_at' => '2024-02-13 13:17:28',
            ],
            [
                'id' => 76,
                'code' => 'VN00083',
                'name' => 'PD Duta Copy Service',
                'address' => 'Jl. Bendungan Hilir Raya No. 36, Jakarta Pusat',
                'phone_number' => '0215701991',
                'email' => 'printing.duta@gmail.com',
                'description' => 'Fotocopy & jilid',
                'contact_person_1' => 'Mr. Iwan Soedewa',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:19:17',
                'updated_at' => '2024-02-13 13:19:17',
            ],
            [
                'id' => 77,
                'code' => 'VN00084',
                'name' => 'Koperasi Reka Sejahtera',
                'address' => 'Jl. Kalibata Timur I No. 36',
                'phone_number' => '0217988700',
                'email' => 'gito@rekayasa.co.id',
                'description' => 'General trading',
                'contact_person_1' => 'Mr. Gito Waluyo',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:22:08',
                'updated_at' => '2024-02-13 13:22:08',
            ],
            [
                'id' => 78,
                'code' => 'VN00085',
                'name' => 'PT Sarana Solusindo Informatika',
                'address' => 'Jl. Sisingamangaraja No. 53 Kebayoran Baru, Jakarta 12110',
                'phone_number' => '0217201419',
                'email' => 'marketing@solusi.com',
                'description' => 'Software license, training center, CAD/CAM solutions, professional services',
                'contact_person_1' => 'Mr. Tri Handaka',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:23:53',
                'updated_at' => '2024-02-13 13:23:53',
            ],
            [
                'id' => 79,
                'code' => 'VN00086',
                'name' => 'PT Abadi Jaya Makmur',
                'address' => 'Jl. Toko Tiga No. 30 Jakarta',
                'phone_number' => '0216911190',
                'email' => 'pd.abadi@yahoo.com',
                'description' => 'Office equipment & home furniture',
                'contact_person_1' => 'Mrs. Meliza',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:30:16',
                'updated_at' => '2024-02-13 13:30:16',
            ],
            [
                'id' => 80,
                'code' => 'VN00087',
                'name' => 'PT Onna Prima Utama',
                'address' => 'Jl. Kapuk Utara I No. 3 Jakarta 14460',
                'phone_number' => '02129328128',
                'email' => 'dwi.lestari@onna.co.id',
                'description' => 'Blinds specialist',
                'contact_person_1' => 'Ms. Dwi Lestari',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:33:44',
                'updated_at' => '2024-02-13 13:33:44',
            ],
            [
                'id' => 81,
                'code' => 'VN00118',
                'name' => 'PT Berkat Niaga Dunia',
                'address' => 'Jl. Cideng Barat No. 47D, Cideng Jakarta Pusat',
                'phone_number' => '0216327060',
                'email' => 'sales@ptdws.co.id',
                'description' => 'PPE & safety gear',
                'contact_person_1' => 'Mr. Kiansun',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:37:12',
                'updated_at' => '2024-02-13 13:37:12',
            ],
            [
                'id' => 82,
                'code' => 'VN00088',
                'name' => 'PT Berca Carrier Indonesia',
                'address' => 'Jl. Pangeran Jayakarta 149B, Jakarta 10730',
                'phone_number' => '085624655504',
                'email' => 'diki.zakaria@carrier.co.id',
                'description' => 'Software Hourly Analysis Program (HAP)',
                'contact_person_1' => 'Mr. Diki Zakaria',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:39:11',
                'updated_at' => '2024-02-13 13:39:11',
            ],
            [
                'id' => 83,
                'code' => 'VN00089',
                'name' => 'PT Mitsubishi Jaya Elevator & Escalator',
                'address' => 'Gd. Jaya Lt. 11 Jl. MH Thamrin No. 12 Jakarta Pusat',
                'phone_number' => '081288101717',
                'email' => 'tata@mjee.co.id',
                'description' => 'Pemeliharaan lift',
                'contact_person_1' => 'Mr. Tata',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:40:39',
                'updated_at' => '2024-02-13 13:40:39',
            ],
            [
                'id' => 84,
                'code' => 'VN00090',
                'name' => 'Codeware, Inc.',
                'address' => '5224 Station Way, Sarasota Floor 34233, PO Box 741888, Atlanta, GA, 30384 - 1888 USA',
                'phone_number' => '9419272670',
                'email' => 'mary.samuels@codeware.com',
                'description' => 'Software COMPRESS',
                'contact_person_1' => 'Mr. Mary Samuels',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:42:46',
                'updated_at' => '2024-02-13 13:42:46',
            ],
            [
                'id' => 85,
                'code' => 'VN00091',
                'name' => 'Bentley Systems International Ltd.',
                'address' => 'Block 2 Upper Floor, Park Place, Upper Hatch Street, Dublin D02 Np94 / IE',
                'phone_number' => '03534364600',
                'email' => 'manisha.shaw@bentley.com',
                'description' => 'Software SACS Offshore',
                'contact_person_1' => 'Ms. Lannawati Kwee',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:45:56',
                'updated_at' => '2024-02-13 13:45:56',
            ],
            [
                'id' => 86,
                'code' => 'VN00092',
                'name' => 'PT Lima Pilar Cakrawala',
                'address' => 'Grand Galaxy City Blok RSA 1 No. 57, Bekasi',
                'phone_number' => '02182732227',
                'email' => 'fitri@lpc.co.id',
                'description' => 'Software & mail server specialist',
                'contact_person_1' => 'Mrs. Fika Safitri',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:47:19',
                'updated_at' => '2024-02-13 13:47:19',
            ],
            [
                'id' => 87,
                'code' => 'VN00093',
                'name' => 'PT Cipta Satria Informatika',
                'address' => 'Jl. Keuangan I No. 11 Cilandak Barat, Jakarta Selatan 12430',
                'phone_number' => '085692962103',
                'email' => 'agung.pramudito@ciptasatria.com',
                'description' => 'Licensed software, computer system & training specialist',
                'contact_person_1' => 'Mr. Agung Pramudito',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:50:05',
                'updated_at' => '2024-02-13 13:50:05',
            ],
            [
                'id' => 88,
                'code' => 'VN00094',
                'name' => 'PT Medatama (Mega Persada Utama)',
                'address' => 'Jl. Raya Inspeksi Saluran Kalimalang, Cipinang Bali III No. 1A, Jakarta Timur',
                'phone_number' => '02186607021',
                'email' => 'medatama100@gmail.com',
                'description' => 'Pemeriksaan, pengujian & re-sertifikasi peralatan K3',
                'contact_person_1' => 'Mr. Cornelis',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:51:23',
                'updated_at' => '2024-02-13 13:51:23',
            ],
            [
                'id' => 89,
                'code' => 'VN00095',
                'name' => 'PT Recare',
                'address' => 'Jl. Kalibata Timur II No. 27 Jakarta Selatan',
                'phone_number' => '021798181180',
                'email' => 'mujiono@recare.rekayasa.co.id',
                'description' => 'MPS, cleaning service',
                'contact_person_1' => 'Mr. Muji',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:52:34',
                'updated_at' => '2024-02-13 13:52:34',
            ],
            [
                'id' => 90,
                'code' => 'VN00096',
                'name' => 'Trimble Solutions SEA Pte. Ltd.',
                'address' => '3 Harbourfront Place #13 - 02 Harbourfront Tower, Singapore 099254',
                'phone_number' => '6562738775',
                'email' => 'tekla.indonesia@buildings.trimble.com',
                'description' => 'Licensed software',
                'contact_person_1' => 'Mr. Leo Yulyardi',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:54:16',
                'updated_at' => '2024-02-13 13:54:16',
            ],
            [
                'id' => 91,
                'code' => 'VN00097',
                'name' => 'PT Parsaoran Global Datatrans',
                'address' => 'Graha Mampang Building 5th Floor, Jl. Mampang Prapatan No. 100 Jakarta 12760',
                'phone_number' => '02129841968',
                'email' => 'ari@hsp.net.id',
                'description' => 'Internet provider - HSPNet',
                'contact_person_1' => 'Ms. Aryani',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 13:55:40',
                'updated_at' => '2024-02-13 13:55:40',
            ],
            [
                'id' => 92,
                'code' => 'VN00098',
                'name' => 'Kayreach System',
                'address' => 'Grand Slipi Tower 35th Floor Unit B - C, Jl. Letjen S Parman Kav. 22 - 24 Slipi, Jakarta Barat',
                'phone_number' => '02129022360',
                'email' => 'marketing@kayreach.com',
                'description' => 'Licensed software',
                'contact_person_1' => 'Mr. Agung Pramudito',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:01:25',
                'updated_at' => '2024-02-13 14:01:25',
            ],
            [
                'id' => 93,
                'code' => 'VN00099',
                'name' => 'Cahaya Jaya Services',
                'address' => '37 Jl. Pemimpin #07 - 07 MAPEX Building, Singapore 577177',
                'phone_number' => '6564814106',
                'email' => 'etap@cbn.net.id',
                'description' => 'Software',
                'contact_person_1' => 'Mr. Moh. Hudri',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:03:02',
                'updated_at' => '2024-02-13 14:03:02',
            ],
            [
                'id' => 94,
                'code' => 'VN00100',
                'name' => 'PT Piranti Sarana Technologi',
                'address' => 'Jl. Hybrida Raya PF 23/7 - 8, Rw. 3, Pegangsaan Dua, Kelapa Gading, Jakarta 14250',
                'phone_number' => '02145865667',
                'email' => 'stef.siswanto@gmail.com',
                'description' => 'Software',
                'contact_person_1' => 'Mr. Siswanto',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:04:48',
                'updated_at' => '2024-02-13 14:04:48',
            ],
            [
                'id' => 95,
                'code' => 'VN00101',
                'name' => 'PT Multi Kharisma',
                'address' => 'Rukan Daan Mogot Baru, Jl. Tampak Siring Blok KJG No. 18',
                'phone_number' => '082211017555',
                'email' => 'kevin@multi-kharisma.com',
                'description' => 'Printer, PC, network',
                'contact_person_1' => 'Mr. Kevin',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:07:05',
                'updated_at' => '2024-02-13 14:07:05',
            ],
            [
                'id' => 96,
                'code' => 'VN00102',
                'name' => 'PT Lippo Insurance Tbk',
                'address' => 'Lippo Kuningan Building Lantai 27 Unit A&F, Jl. H.R. Rasuna Said Kav. B - 12 Jakarta Selatan',
                'phone_number' => '08170760300',
                'email' => 'marketing01.gatsu@lippoinsurance.com',
                'description' => 'Asuransi gedung',
                'contact_person_1' => 'Yuli Saputro',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:08:38',
                'updated_at' => '2024-02-13 14:08:38',
            ],
            [
                'id' => 97,
                'code' => 'VN00103',
                'name' => 'PT Mitralab Buana',
                'address' => 'Jl. Agung Raya II No. 14 Lenteng Agung Jakarta Selatan',
                'phone_number' => '082172276415',
                'email' => 'info@mitralabbuana.co.id',
                'description' => 'Uji kualitas lingkungan',
                'contact_person_1' => 'Syahrul Amri',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:10:18',
                'updated_at' => '2024-02-13 14:10:18',
            ],
            [
                'id' => 98,
                'code' => 'VN00104',
                'name' => 'PT Arya Sentra Solusindo',
                'address' => 'Jl. Abdul Majid Raya No. 33 Cipete Selatan, Jakarta Selatan',
                'phone_number' => '082246460645',
                'email' => 'aryasentraconsulting@gmail.com',
                'description' => 'Jasa konsultasi dan training',
                'contact_person_1' => 'Angga',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:25:24',
                'updated_at' => '2024-02-13 14:25:24',
            ],
            [
                'id' => 99,
                'code' => 'VN00105',
                'name' => 'PT Praba Sinergi Utama',
                'address' => 'The Vida 7th Floor, Jl. Raya Perjuangan No. 8 Kebon Jeruk Jakarta Barat 11530 Indonesia',
                'phone_number' => '087887547599',
                'email' => 'nico.putra02@gmail.com',
                'description' => 'Jasa konsultasi dan training',
                'contact_person_1' => 'Nico',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:26:55',
                'updated_at' => '2024-02-13 14:26:55',
            ],
            [
                'id' => 100,
                'code' => 'VN00106',
                'name' => 'Anril Film',
                'address' => 'Jl. Dr Ide Anak Agung Gde Agung Lot 8, 9/A9 Labtek II Building, 2nd Floor, Jl. Ganesa 10 Bandung 40132Gedung Kantor Taman A9 Unit C5 Lantai 3, Kuningan Timur Setiabudi, Jakarta Selatan',
                'phone_number' => '0816600130',
                'email' => 'kaufik@anril.com',
                'description' => 'Jasa foto aerial & video udara serta company profile',
                'contact_person_1' => 'Kaufik Anril',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:28:54',
                'updated_at' => '2024-02-13 14:28:54',
            ],
            [
                'id' => 101,
                'code' => 'VN00107',
                'name' => 'Beat Studio',
                'address' => 'Mangkuluhur City Office 18th Floor, Jl. Gatot Subroto No. Kav. 2 - 3, RT. 1 / RW. 4, Karet Semanggi, Setiabudi, Jakarta',
                'phone_number' => '02127883335',
                'email' => 'txxj@thebeat.co',
                'description' => 'Jasa pemasaran perdagangan digital dan platrom pertukaran iklan',
                'contact_person_1' => 'Julius Tio',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:42:29',
                'updated_at' => '2024-02-13 14:42:29',
            ],
            [
                'id' => 102,
                'code' => 'VN00108',
                'name' => 'PT Prismaco',
                'address' => 'Jl. Siliwangi No. 56, Sepanjang Jaya, Bekasi',
                'phone_number' => '02182427670',
                'email' => 'ahmad.haekal@prismaco.co.id',
                'description' => 'Jasa penjualan dan sewa mesin fotocopy beserta layanan purna jualnya',
                'contact_person_1' => 'Haekal',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:46:37',
                'updated_at' => '2024-02-13 14:46:37',
            ],
            [
                'id' => 103,
                'code' => 'VN00109',
                'name' => 'PT Kelola Buana Lestari',
                'address' => 'Jl. Durian B.3 No. 1 Angkasa Puri Jati Asih, Bekasi',
                'phone_number' => '082211777203',
                'email' => 'kelola.buana@gmail.com',
                'description' => 'Pengelolaan limbah bahan berbahaya dan beracun (B3)',
                'contact_person_1' => 'Okky',
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-02-13 14:48:47',
                'updated_at' => '2024-02-13 14:48:47',
            ],
            [
                'id' => 104,
                'code' => 'VN00110',
                'name' => 'Intact Official Store',
                'address' => 'Tokopedia',
                'phone_number' => '12345678',
                'email' => 'tokopedia@gmail.com',
                'description' => 'Seller brand V-Gen & Orico',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-03-26 14:30:08',
                'updated_at' => '2024-03-26 14:30:08',
            ],
            [
                'id' => 105,
                'code' => 'VN00111',
                'name' => 'Tokopedia',
                'address' => 'Toko Online',
                'phone_number' => '12345678',
                'email' => 'tokopedia@gmail.com',
                'description' => 'Toko online',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-09-24 09:38:14',
                'updated_at' => '2024-09-24 09:38:14',
            ],
            [
                'id' => 106,
                'code' => 'VN00112',
                'name' => 'Titis',
                'address' => 'Jakarta',
                'phone_number' => '12345678',
                'email' => 'titis@gmail.com',
                'description' => 'Vendor project Iwan Kurniawan',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2024-09-24 11:01:31',
                'updated_at' => '2024-09-24 11:01:31',
            ],
            [
                'id' => 107,
                'code' => 'VN00113',
                'name' => 'Sunio Citra Teknologi',
                'address' => 'Rukan City Square Blok C No. 15, Jl. Peta Selatan Jakarta 11840',
                'phone_number' => '02154338150',
                'email' => 'tommy@suniocitra.com',
                'description' => 'www.suniocitra.com',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2025-02-11 14:15:51',
                'updated_at' => '2025-02-11 14:15:51',
            ],
            [
                'id' => 108,
                'code' => 'VN00114',
                'name' => 'Sarana Solusindo Prima',
                'address' => 'Jl. Bungur Besar No. 46X, Jakarta Pusat 10610',
                'phone_number' => '02142876596',
                'email' => 'sales@saranasolusindoprima.com',
                'description' => 'Ph. (021)4287-6596,4287-6602',
                'contact_person_1' => null,
                'cp_email_1' => null,
                'cp_phone_1' => null,
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2025-02-11 14:18:39',
                'updated_at' => '2025-02-11 14:18:39',
            ],
            [
                'id' => 109,
                'code' => 'VN00115',
                'name' => 'PT Cipta Tekno Solusindo',
                'address' => 'Tangerang',
                'phone_number' => '02179181180',
                'email' => 'marketing@solusindo.com',
                'description' => 'Vendor IT',
                'contact_person_1' => 'Windy',
                'cp_email_1' => null,
                'cp_phone_1' => '089608366897',
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2026-05-19 16:32:19',
                'updated_at' => '2026-05-19 16:32:19',
            ],
            [
                'id' => 110,
                'code' => 'VN00116',
                'name' => 'PT United Teknologi Integrasi',
                'address' => 'Blok 21 Building, Jl. Siantar No. 18 Cideng, Jakarta Pusat 10150',
                'phone_number' => '081806994548',
                'email' => 'sales@uti.co.id',
                'description' => 'Vendor IT',
                'contact_person_1' => 'Misar Sulaeman',
                'cp_email_1' => null,
                'cp_phone_1' => '081806994548',
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2026-08-31 09:56:27',
                'updated_at' => '2026-08-31 09:56:27',
            ],
            [
                'id' => 111,
                'code' => 'VN00117',
                'name' => 'PT Sparta Computindo Teknologi',
                'address' => 'Jl. Raya Lenteng Agung Barat No. 8 Serengseng Sawah Jagakarsa',
                'phone_number' => '087780149485',
                'email' => 'sparta_computindo@yahoo.co.id',
                'description' => 'Vendor server',
                'contact_person_1' => 'Iman',
                'cp_email_1' => null,
                'cp_phone_1' => '087780149485',
                'contact_person_2' => null,
                'cp_email_2' => null,
                'cp_phone_2' => null,
                'created_at' => '2026-09-18 17:28:22',
                'updated_at' => '2026-09-18 17:28:22',
            ],
        ];

        $isSqlsrv = DB::connection()->getDriverName() === 'sqlsrv';

        if ($isSqlsrv) {
            DB::unprepared('SET IDENTITY_INSERT vendors ON;');
        }

        foreach (array_chunk($records, 100) as $chunk) {
            DB::table('vendors')->upsert(
                $chunk,
                ['id'],
                [
                    'code',
                    'name',
                    'address',
                    'phone_number',
                    'email',
                    'description',
                    'contact_person_1',
                    'cp_email_1',
                    'cp_phone_1',
                    'contact_person_2',
                    'cp_email_2',
                    'cp_phone_2',
                    'updated_at',
                ]
            );
        }

        if ($isSqlsrv) {
            DB::unprepared('SET IDENTITY_INSERT vendors OFF;');
        }
    }
}
