<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActualLocationSeeder extends Seeder
{
    /**
     * Run the master Location database seeds.
     * Ordered topologically to ensure parents are seeded before children.
     * Total records: 171
     */
    public function run(): void
    {
        $records = [
            [
                'id' => 36,
                'name' => 'Graha RE 1',
                'parent_id' => null,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:02:54',
                'updated_at' => '2016-12-08 15:02:54',
            ],
            [
                'id' => 37,
                'name' => 'Graha RE 2',
                'parent_id' => null,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:03:03',
                'updated_at' => '2016-12-08 15:03:03',
            ],
            [
                'id' => 77,
                'name' => 'NODATA',
                'parent_id' => null,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-04 15:18:18',
                'updated_at' => '2017-01-04 15:18:18',
            ],
            [
                'id' => 213,
                'name' => 'Others Building',
                'parent_id' => null,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-02-20 11:07:31',
                'updated_at' => '2017-02-20 11:07:31',
            ],
            [
                'id' => 38,
                'name' => 'Lantai Mezzanine',
                'parent_id' => 36,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:12:03',
                'updated_at' => '2016-12-08 15:12:03',
            ],
            [
                'id' => 39,
                'name' => 'Lantai 1',
                'parent_id' => 36,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:12:10',
                'updated_at' => '2016-12-08 15:12:10',
            ],
            [
                'id' => 41,
                'name' => 'Lantai 2',
                'parent_id' => 36,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:13:05',
                'updated_at' => '2016-12-08 15:13:05',
            ],
            [
                'id' => 42,
                'name' => 'Lantai 3',
                'parent_id' => 36,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:13:12',
                'updated_at' => '2016-12-08 15:13:12',
            ],
            [
                'id' => 44,
                'name' => 'Basement',
                'parent_id' => 37,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:13:51',
                'updated_at' => '2016-12-08 15:13:51',
            ],
            [
                'id' => 45,
                'name' => 'Mezzanine',
                'parent_id' => 37,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:13:59',
                'updated_at' => '2016-12-08 15:13:59',
            ],
            [
                'id' => 46,
                'name' => 'Lantai 1',
                'parent_id' => 37,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:14:06',
                'updated_at' => '2016-12-08 15:14:06',
            ],
            [
                'id' => 47,
                'name' => 'Lantai 2',
                'parent_id' => 37,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2016-12-08 15:14:59',
                'updated_at' => '2016-12-08 15:14:59',
            ],
            [
                'id' => 80,
                'name' => 'Lantai 4',
                'parent_id' => 36,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:18:26',
                'updated_at' => '2017-01-19 09:18:26',
            ],
            [
                'id' => 179,
                'name' => 'Top Floor',
                'parent_id' => 37,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:14:10',
                'updated_at' => '2017-01-19 10:14:10',
            ],
            [
                'id' => 214,
                'name' => 'Others Floor',
                'parent_id' => 213,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2018-04-26 08:16:05',
                'updated_at' => '2018-04-26 08:16:05',
            ],
            [
                'id' => 81,
                'name' => 'Halaman Selatan',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:41:02',
                'updated_at' => '2017-01-19 09:41:02',
            ],
            [
                'id' => 82,
                'name' => 'Halaman Timur',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:41:16',
                'updated_at' => '2017-01-19 09:41:16',
            ],
            [
                'id' => 83,
                'name' => 'Halaman Barat',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:41:38',
                'updated_at' => '2017-01-19 09:41:38',
            ],
            [
                'id' => 84,
                'name' => 'Halaman Utara',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:41:49',
                'updated_at' => '2017-01-19 09:41:49',
            ],
            [
                'id' => 85,
                'name' => 'Koperasi',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:42:11',
                'updated_at' => '2017-01-19 09:42:11',
            ],
            [
                'id' => 86,
                'name' => 'Gudang Recon',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:42:29',
                'updated_at' => '2017-01-19 09:42:29',
            ],
            [
                'id' => 87,
                'name' => 'Gardu PLN',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:42:42',
                'updated_at' => '2017-01-19 09:42:42',
            ],
            [
                'id' => 88,
                'name' => 'Smoking Room',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:43:12',
                'updated_at' => '2017-01-19 09:43:12',
            ],
            [
                'id' => 89,
                'name' => 'Kantin',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:43:24',
                'updated_at' => '2017-01-19 09:43:24',
            ],
            [
                'id' => 90,
                'name' => 'Driver Room',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:43:51',
                'updated_at' => '2017-01-19 09:43:51',
            ],
            [
                'id' => 91,
                'name' => 'SOS Room',
                'parent_id' => 38,
                'related_departement' => 94,
                'is_active' => true,
                'created_at' => '2017-01-19 09:46:48',
                'updated_at' => '2017-01-19 09:46:48',
            ],
            [
                'id' => 92,
                'name' => 'Area STP',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:47:12',
                'updated_at' => '2017-01-19 09:47:12',
            ],
            [
                'id' => 93,
                'name' => 'Pump Room',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:47:33',
                'updated_at' => '2017-01-19 09:47:33',
            ],
            [
                'id' => 94,
                'name' => 'Pos Security',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:47:54',
                'updated_at' => '2017-01-19 09:47:54',
            ],
            [
                'id' => 95,
                'name' => 'Lobby Utama',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:48:05',
                'updated_at' => '2017-01-19 09:48:05',
            ],
            [
                'id' => 96,
                'name' => 'Koridor Selatan',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:48:16',
                'updated_at' => '2017-01-19 09:48:16',
            ],
            [
                'id' => 98,
                'name' => 'Koridor Utara',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:49:14',
                'updated_at' => '2017-01-19 09:49:14',
            ],
            [
                'id' => 99,
                'name' => 'Koridor Barat',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:49:37',
                'updated_at' => '2017-01-19 09:49:37',
            ],
            [
                'id' => 100,
                'name' => 'Toilet Wanita',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:49:51',
                'updated_at' => '2017-01-19 09:49:51',
            ],
            [
                'id' => 101,
                'name' => 'Toilet Pria',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:50:08',
                'updated_at' => '2017-01-19 09:50:08',
            ],
            [
                'id' => 102,
                'name' => 'Panel Listrik Barat',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:50:22',
                'updated_at' => '2017-01-19 09:50:22',
            ],
            [
                'id' => 103,
                'name' => 'Panel Listrik Utara',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:50:40',
                'updated_at' => '2017-01-19 09:50:40',
            ],
            [
                'id' => 104,
                'name' => 'Ruang Panel',
                'parent_id' => 38,
                'related_departement' => 93,
                'is_active' => true,
                'created_at' => '2017-01-19 09:50:49',
                'updated_at' => '2017-01-19 09:50:49',
            ],
            [
                'id' => 105,
                'name' => 'Panel IT Utara',
                'parent_id' => 38,
                'related_departement' => 93,
                'is_active' => true,
                'created_at' => '2017-01-19 09:51:04',
                'updated_at' => '2017-01-19 09:51:04',
            ],
            [
                'id' => 106,
                'name' => 'Panel AC AHU',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:51:22',
                'updated_at' => '2017-01-19 09:51:22',
            ],
            [
                'id' => 107,
                'name' => 'Area Tangga Darurat',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:51:47',
                'updated_at' => '2017-01-19 09:51:47',
            ],
            [
                'id' => 108,
                'name' => 'Area Tangga Utama',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:52:13',
                'updated_at' => '2017-01-19 09:52:13',
            ],
            [
                'id' => 109,
                'name' => 'Pantry',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:52:25',
                'updated_at' => '2017-01-19 09:52:25',
            ],
            [
                'id' => 110,
                'name' => 'Dokter & Laktasi',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:52:44',
                'updated_at' => '2017-01-19 09:52:44',
            ],
            [
                'id' => 111,
                'name' => 'Ruang Meeting Sidoasih',
                'parent_id' => 44,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:53:00',
                'updated_at' => '2017-01-19 09:53:00',
            ],
            [
                'id' => 112,
                'name' => 'Ruang Meeting Truntum',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:53:16',
                'updated_at' => '2017-01-19 09:53:16',
            ],
            [
                'id' => 113,
                'name' => 'Ex Document Room',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:53:28',
                'updated_at' => '2017-01-19 09:53:28',
            ],
            [
                'id' => 114,
                'name' => 'ICT Department',
                'parent_id' => 38,
                'related_departement' => 93,
                'is_active' => true,
                'created_at' => '2017-01-19 09:53:53',
                'updated_at' => '2017-01-19 09:53:53',
            ],
            [
                'id' => 115,
                'name' => 'HRM Department',
                'parent_id' => 38,
                'related_departement' => 92,
                'is_active' => true,
                'created_at' => '2017-01-19 09:54:05',
                'updated_at' => '2017-01-19 09:54:05',
            ],
            [
                'id' => 116,
                'name' => 'CFS Department',
                'parent_id' => 38,
                'related_departement' => 94,
                'is_active' => true,
                'created_at' => '2017-01-19 09:54:17',
                'updated_at' => '2017-01-19 09:54:17',
            ],
            [
                'id' => 117,
                'name' => 'PPC Department',
                'parent_id' => 38,
                'related_departement' => 102,
                'is_active' => true,
                'created_at' => '2017-01-19 09:54:28',
                'updated_at' => '2017-01-19 09:54:28',
            ],
            [
                'id' => 118,
                'name' => 'Area Kerja Umum',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:54:37',
                'updated_at' => '2017-01-19 09:54:37',
            ],
            [
                'id' => 119,
                'name' => 'ICT Training Room',
                'parent_id' => 38,
                'related_departement' => 93,
                'is_active' => true,
                'created_at' => '2017-01-19 09:54:51',
                'updated_at' => '2017-01-19 09:54:51',
            ],
            [
                'id' => 120,
                'name' => '3DD Department Barat',
                'parent_id' => 38,
                'related_departement' => 109,
                'is_active' => true,
                'created_at' => '2017-01-19 09:55:04',
                'updated_at' => '2017-01-19 09:55:04',
            ],
            [
                'id' => 121,
                'name' => '3DD Department Timur',
                'parent_id' => 38,
                'related_departement' => 109,
                'is_active' => true,
                'created_at' => '2017-01-19 09:55:24',
                'updated_at' => '2017-01-19 09:55:24',
            ],
            [
                'id' => 122,
                'name' => 'Lift',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:55:35',
                'updated_at' => '2017-01-19 09:55:35',
            ],
            [
                'id' => 123,
                'name' => 'Koridor Utara',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:55:55',
                'updated_at' => '2017-01-19 09:55:55',
            ],
            [
                'id' => 124,
                'name' => 'Koridor Selatan',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:56:00',
                'updated_at' => '2017-01-19 09:56:00',
            ],
            [
                'id' => 125,
                'name' => 'Koridor Barat',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:56:05',
                'updated_at' => '2017-01-19 09:56:05',
            ],
            [
                'id' => 127,
                'name' => 'Toilet Pria',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:56:22',
                'updated_at' => '2017-01-19 09:56:22',
            ],
            [
                'id' => 128,
                'name' => 'Toilet Wanita',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:56:29',
                'updated_at' => '2017-01-19 09:56:29',
            ],
            [
                'id' => 129,
                'name' => 'Musholla Pria',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:56:43',
                'updated_at' => '2017-01-19 09:56:43',
            ],
            [
                'id' => 130,
                'name' => 'Musholla Wanita',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:56:57',
                'updated_at' => '2017-01-19 09:56:57',
            ],
            [
                'id' => 131,
                'name' => 'Panel AC AHU',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:57:07',
                'updated_at' => '2017-01-19 09:57:07',
            ],
            [
                'id' => 132,
                'name' => 'Ruang Meeting Rasamala',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:57:22',
                'updated_at' => '2017-01-19 09:57:22',
            ],
            [
                'id' => 133,
                'name' => 'Ruang Meeting Sidomukti',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:57:42',
                'updated_at' => '2017-01-19 09:57:42',
            ],
            [
                'id' => 134,
                'name' => 'Area Kerja Umum Selatan',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:57:57',
                'updated_at' => '2017-01-19 09:57:57',
            ],
            [
                'id' => 135,
                'name' => 'Area Kerja Umum Utara',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:58:12',
                'updated_at' => '2017-01-19 09:58:12',
            ],
            [
                'id' => 136,
                'name' => 'General Manager Room',
                'parent_id' => 39,
                'related_departement' => 99,
                'is_active' => true,
                'created_at' => '2017-01-19 09:58:26',
                'updated_at' => '2017-01-19 09:58:26',
            ],
            [
                'id' => 137,
                'name' => 'Project Manager Room',
                'parent_id' => 39,
                'related_departement' => 99,
                'is_active' => true,
                'created_at' => '2017-01-19 09:58:39',
                'updated_at' => '2017-01-19 09:58:39',
            ],
            [
                'id' => 138,
                'name' => 'Marketing Department',
                'parent_id' => 39,
                'related_departement' => 95,
                'is_active' => true,
                'created_at' => '2017-01-19 09:58:52',
                'updated_at' => '2017-01-19 09:58:52',
            ],
            [
                'id' => 139,
                'name' => 'Piping & Mechanical Department Barat',
                'parent_id' => 39,
                'related_departement' => 105,
                'is_active' => true,
                'created_at' => '2017-01-19 09:59:21',
                'updated_at' => '2017-01-19 09:59:21',
            ],
            [
                'id' => 140,
                'name' => 'Piping & Mechanical Department Timur',
                'parent_id' => 39,
                'related_departement' => 105,
                'is_active' => true,
                'created_at' => '2017-01-19 09:59:38',
                'updated_at' => '2017-01-19 09:59:38',
            ],
            [
                'id' => 141,
                'name' => 'Area Tangga Darurat',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:00:01',
                'updated_at' => '2017-01-19 10:00:01',
            ],
            [
                'id' => 142,
                'name' => 'Koridor Tangga Luar',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:00:47',
                'updated_at' => '2017-01-19 10:00:47',
            ],
            [
                'id' => 143,
                'name' => 'Koridor Utara',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:01:13',
                'updated_at' => '2017-01-19 10:01:13',
            ],
            [
                'id' => 144,
                'name' => 'Koridor Barat',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:01:18',
                'updated_at' => '2017-01-19 10:01:18',
            ],
            [
                'id' => 145,
                'name' => 'Toilet Pria',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:01:23',
                'updated_at' => '2017-01-19 10:01:23',
            ],
            [
                'id' => 146,
                'name' => 'Toilet Wanita',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:01:29',
                'updated_at' => '2017-01-19 10:01:29',
            ],
            [
                'id' => 147,
                'name' => 'Toilet VIP',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:01:41',
                'updated_at' => '2017-01-19 10:01:41',
            ],
            [
                'id' => 148,
                'name' => 'Pantry',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:01:48',
                'updated_at' => '2017-01-19 10:01:48',
            ],
            [
                'id' => 149,
                'name' => 'Area Sekretaris',
                'parent_id' => 41,
                'related_departement' => 94,
                'is_active' => true,
                'created_at' => '2017-01-19 10:01:57',
                'updated_at' => '2017-01-19 10:01:57',
            ],
            [
                'id' => 150,
                'name' => 'Area Tangga Darurat',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:02:12',
                'updated_at' => '2017-01-19 10:02:12',
            ],
            [
                'id' => 151,
                'name' => 'Ruang Meeting Parangkusumo',
                'parent_id' => 41,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:02:43',
                'updated_at' => '2017-01-19 10:02:43',
            ],
            [
                'id' => 153,
                'name' => 'Finance Department Timur',
                'parent_id' => 41,
                'related_departement' => 91,
                'is_active' => true,
                'created_at' => '2017-01-19 10:02:59',
                'updated_at' => '2017-01-19 10:02:59',
            ],
            [
                'id' => 154,
                'name' => 'Finance Department Barat',
                'parent_id' => 41,
                'related_departement' => 91,
                'is_active' => true,
                'created_at' => '2017-01-19 10:03:18',
                'updated_at' => '2017-01-19 10:03:18',
            ],
            [
                'id' => 155,
                'name' => 'Ruang Direktur Utama',
                'parent_id' => 41,
                'related_departement' => 77,
                'is_active' => true,
                'created_at' => '2017-01-19 10:03:30',
                'updated_at' => '2017-01-19 10:03:30',
            ],
            [
                'id' => 156,
                'name' => 'Ruang Direktur Operasional',
                'parent_id' => 41,
                'related_departement' => 89,
                'is_active' => true,
                'created_at' => '2017-01-19 10:03:45',
                'updated_at' => '2017-01-19 10:03:45',
            ],
            [
                'id' => 157,
                'name' => 'Ruang Direktur Keuangan dan Infrastruktur',
                'parent_id' => 41,
                'related_departement' => 90,
                'is_active' => true,
                'created_at' => '2017-01-19 10:04:15',
                'updated_at' => '2017-01-19 10:04:15',
            ],
            [
                'id' => 158,
                'name' => 'Koridor Utara',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:04:27',
                'updated_at' => '2017-01-19 10:04:27',
            ],
            [
                'id' => 159,
                'name' => 'Koridor Barat',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:04:32',
                'updated_at' => '2017-01-19 10:04:32',
            ],
            [
                'id' => 160,
                'name' => 'Toilet Pria',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:04:38',
                'updated_at' => '2017-01-19 10:04:38',
            ],
            [
                'id' => 161,
                'name' => 'Toilet Wanita',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:04:42',
                'updated_at' => '2017-01-19 10:04:42',
            ],
            [
                'id' => 162,
                'name' => 'Pantry',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:04:47',
                'updated_at' => '2017-01-19 10:04:47',
            ],
            [
                'id' => 163,
                'name' => 'Ruang Fotokopi',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:04:55',
                'updated_at' => '2017-01-19 10:04:55',
            ],
            [
                'id' => 164,
                'name' => 'Ruang Meeting Megamendung',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:05:15',
                'updated_at' => '2017-01-19 10:05:15',
            ],
            [
                'id' => 165,
                'name' => 'Civil Department Timur',
                'parent_id' => 42,
                'related_departement' => 106,
                'is_active' => true,
                'created_at' => '2017-01-19 10:05:28',
                'updated_at' => '2017-01-19 10:05:28',
            ],
            [
                'id' => 166,
                'name' => 'Civil Department Barat',
                'parent_id' => 42,
                'related_departement' => 106,
                'is_active' => true,
                'created_at' => '2017-01-19 10:05:37',
                'updated_at' => '2017-01-19 10:05:37',
            ],
            [
                'id' => 167,
                'name' => 'Tangga Darurat',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:05:52',
                'updated_at' => '2017-01-19 10:05:52',
            ],
            [
                'id' => 168,
                'name' => 'Koridor Utara',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:07:00',
                'updated_at' => '2017-01-19 10:07:00',
            ],
            [
                'id' => 169,
                'name' => 'Area Tangga Darurat',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:07:08',
                'updated_at' => '2017-01-19 10:07:08',
            ],
            [
                'id' => 170,
                'name' => 'Ruang AC AHU',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:07:25',
                'updated_at' => '2017-01-19 10:07:25',
            ],
            [
                'id' => 171,
                'name' => 'Toilet Pria',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:07:31',
                'updated_at' => '2017-01-19 10:07:31',
            ],
            [
                'id' => 172,
                'name' => 'Toilet Wanita',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:07:35',
                'updated_at' => '2017-01-19 10:07:35',
            ],
            [
                'id' => 173,
                'name' => 'Pantry',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:07:40',
                'updated_at' => '2017-01-19 10:07:40',
            ],
            [
                'id' => 174,
                'name' => 'Ruang Meeting Sekarjagat',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:07:56',
                'updated_at' => '2017-01-19 10:07:56',
            ],
            [
                'id' => 175,
                'name' => 'Instrument Department',
                'parent_id' => 80,
                'related_departement' => 108,
                'is_active' => true,
                'created_at' => '2017-01-19 10:08:10',
                'updated_at' => '2017-01-19 10:08:10',
            ],
            [
                'id' => 176,
                'name' => 'Process Department',
                'parent_id' => 80,
                'related_departement' => 103,
                'is_active' => false,
                'created_at' => '2017-01-19 10:08:23',
                'updated_at' => '2017-01-19 10:08:23',
            ],
            [
                'id' => 177,
                'name' => 'Rumah Lift',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:08:33',
                'updated_at' => '2017-01-19 10:08:33',
            ],
            [
                'id' => 178,
                'name' => 'Koridor Luar',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:08:44',
                'updated_at' => '2017-01-19 10:08:44',
            ],
            [
                'id' => 180,
                'name' => 'Area Tangga',
                'parent_id' => 44,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:15:07',
                'updated_at' => '2017-01-19 10:15:07',
            ],
            [
                'id' => 181,
                'name' => 'Gudang',
                'parent_id' => 44,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:15:13',
                'updated_at' => '2017-01-19 10:15:13',
            ],
            [
                'id' => 182,
                'name' => 'Koridor Luar',
                'parent_id' => 44,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:15:20',
                'updated_at' => '2017-01-19 10:15:20',
            ],
            [
                'id' => 183,
                'name' => 'Ruang Meeting Tiga Negeri',
                'parent_id' => 44,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:15:36',
                'updated_at' => '2017-01-19 10:15:36',
            ],
            [
                'id' => 184,
                'name' => 'Halaman Utara',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:15:50',
                'updated_at' => '2017-01-19 10:15:50',
            ],
            [
                'id' => 185,
                'name' => 'Lobby Utama',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:15:57',
                'updated_at' => '2017-01-19 10:15:57',
            ],
            [
                'id' => 186,
                'name' => 'Toilet Pria',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:16:02',
                'updated_at' => '2017-01-19 10:16:02',
            ],
            [
                'id' => 187,
                'name' => 'Toilet Wanita',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:16:05',
                'updated_at' => '2017-01-19 10:16:05',
            ],
            [
                'id' => 188,
                'name' => 'Toilet 2',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:16:12',
                'updated_at' => '2017-01-19 10:16:12',
            ],
            [
                'id' => 189,
                'name' => 'Pantry',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:16:16',
                'updated_at' => '2017-01-19 10:16:16',
            ],
            [
                'id' => 190,
                'name' => 'Musholla',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:16:28',
                'updated_at' => '2017-01-19 10:16:28',
            ],
            [
                'id' => 191,
                'name' => 'Server & Panel Room',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:16:42',
                'updated_at' => '2017-01-19 10:16:42',
            ],
            [
                'id' => 192,
                'name' => 'Ruang Electrical',
                'parent_id' => 45,
                'related_departement' => 107,
                'is_active' => false,
                'created_at' => '2017-01-19 10:16:52',
                'updated_at' => '2017-01-19 10:16:52',
            ],
            [
                'id' => 193,
                'name' => 'Tangga Menuju Lt1',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:17:00',
                'updated_at' => '2017-01-19 10:17:00',
            ],
            [
                'id' => 194,
                'name' => 'Menuju Lt2',
                'parent_id' => 46,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:17:17',
                'updated_at' => '2017-01-19 10:17:17',
            ],
            [
                'id' => 195,
                'name' => 'Ruang Meeting Pisan Bali',
                'parent_id' => 46,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:17:33',
                'updated_at' => '2017-01-19 10:17:33',
            ],
            [
                'id' => 196,
                'name' => 'Ruang Meeting Recare',
                'parent_id' => 46,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:17:49',
                'updated_at' => '2017-01-19 10:17:49',
            ],
            [
                'id' => 197,
                'name' => 'Ruang Recare',
                'parent_id' => 46,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:17:58',
                'updated_at' => '2017-01-19 10:17:58',
            ],
            [
                'id' => 198,
                'name' => 'Toilet',
                'parent_id' => 46,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:18:06',
                'updated_at' => '2017-01-19 10:18:06',
            ],
            [
                'id' => 199,
                'name' => 'Tangga Menuju Top Floor',
                'parent_id' => 47,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:18:36',
                'updated_at' => '2017-01-19 10:18:36',
            ],
            [
                'id' => 200,
                'name' => 'Toilet',
                'parent_id' => 47,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:18:40',
                'updated_at' => '2017-01-19 10:18:40',
            ],
            [
                'id' => 201,
                'name' => 'Ruang Direktur Utama Recon',
                'parent_id' => 47,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:19:01',
                'updated_at' => '2017-01-19 10:19:01',
            ],
            [
                'id' => 202,
                'name' => 'Ruang Direktur Operasional',
                'parent_id' => 47,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:19:11',
                'updated_at' => '2017-01-19 10:19:11',
            ],
            [
                'id' => 203,
                'name' => 'Ruang Keuangan',
                'parent_id' => 47,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:19:24',
                'updated_at' => '2017-01-19 10:19:24',
            ],
            [
                'id' => 204,
                'name' => 'Area Kerja Timur',
                'parent_id' => 47,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:19:34',
                'updated_at' => '2017-01-19 10:19:34',
            ],
            [
                'id' => 205,
                'name' => 'Area Kerja Barat',
                'parent_id' => 47,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:19:40',
                'updated_at' => '2017-01-19 10:19:40',
            ],
            [
                'id' => 206,
                'name' => 'Ruang Meeting Kembang Kantil',
                'parent_id' => 179,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:20:00',
                'updated_at' => '2017-01-19 10:20:00',
            ],
            [
                'id' => 207,
                'name' => 'Ruang Meeting Ratu Ratih',
                'parent_id' => 179,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:20:13',
                'updated_at' => '2017-01-19 10:20:13',
            ],
            [
                'id' => 208,
                'name' => 'Toilet Pria',
                'parent_id' => 179,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:21:47',
                'updated_at' => '2017-01-19 10:21:47',
            ],
            [
                'id' => 209,
                'name' => 'Toilet Wanita',
                'parent_id' => 179,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:21:51',
                'updated_at' => '2017-01-19 10:21:51',
            ],
            [
                'id' => 210,
                'name' => 'Koridor Dalam',
                'parent_id' => 179,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:22:02',
                'updated_at' => '2017-01-19 10:22:02',
            ],
            [
                'id' => 211,
                'name' => 'Ruang Janitor',
                'parent_id' => 179,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 10:22:09',
                'updated_at' => '2017-01-19 10:22:09',
            ],
            [
                'id' => 215,
                'name' => 'Others Room',
                'parent_id' => 214,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2018-04-26 08:17:01',
                'updated_at' => '2018-04-26 08:17:01',
            ],
            [
                'id' => 218,
                'name' => 'Ruang Meeting Kawung',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2019-11-18 09:11:15',
                'updated_at' => '2019-11-18 09:11:15',
            ],
            [
                'id' => 220,
                'name' => 'Ruang SDQA',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:57:42',
                'updated_at' => '2017-01-19 09:57:42',
            ],
            [
                'id' => 221,
                'name' => 'Ruang Electrical',
                'parent_id' => 42,
                'related_departement' => 107,
                'is_active' => true,
                'created_at' => '2017-01-19 10:05:15',
                'updated_at' => '2017-01-19 10:05:15',
            ],
            [
                'id' => 222,
                'name' => 'Ruang HSE',
                'parent_id' => 38,
                'related_departement' => 97,
                'is_active' => true,
                'created_at' => '2017-01-19 10:17:00',
                'updated_at' => '2017-01-19 10:17:00',
            ],
            [
                'id' => 223,
                'name' => 'Ruang IFS',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 224,
                'name' => 'Ruang SDD',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 225,
                'name' => 'Ruang CSS',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 226,
                'name' => 'GM Marketing',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 227,
                'name' => 'Ruang DM',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 228,
                'name' => 'Recon',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 229,
                'name' => 'Legal',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 230,
                'name' => 'Audit',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 231,
                'name' => 'Departemen Process',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 232,
                'name' => 'Departemen Civil',
                'parent_id' => 42,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 233,
                'name' => 'Ruang Proyek',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 234,
                'name' => 'Ruang Recare',
                'parent_id' => 45,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 235,
                'name' => 'Ruang Kelas Recare',
                'parent_id' => 179,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2023-06-13 10:17:00',
                'updated_at' => '2023-06-13 10:17:00',
            ],
            [
                'id' => 236,
                'name' => 'Mega Mendung Space',
                'parent_id' => 80,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-02-28 00:00:00',
                'updated_at' => '2024-02-28 00:00:00',
            ],
            [
                'id' => 237,
                'name' => 'Ruang Server RETO',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-03-20 10:17:00',
                'updated_at' => '2024-03-20 10:17:00',
            ],
            [
                'id' => 238,
                'name' => 'Ruang General Manager',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-03-20 10:17:00',
                'updated_at' => '2024-03-20 10:17:00',
            ],
            [
                'id' => 239,
                'name' => 'Ruang Proyek',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-03-20 10:17:00',
                'updated_at' => '2024-03-20 10:17:00',
            ],
            [
                'id' => 240,
                'name' => 'Pantry',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-03-20 10:17:00',
                'updated_at' => '2024-03-20 10:17:00',
            ],
            [
                'id' => 241,
                'name' => 'Ruang Proyek',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-05-02 10:17:00',
                'updated_at' => '2024-05-02 10:17:00',
            ],
            [
                'id' => 242,
                'name' => 'Departemen Instrument',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-05-02 10:17:00',
                'updated_at' => '2024-05-02 10:17:00',
            ],
            [
                'id' => 243,
                'name' => 'Ruang Project Freeport',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-07-23 00:00:00',
                'updated_at' => '2024-07-23 00:00:00',
            ],
            [
                'id' => 244,
                'name' => 'Ruang Project PHR',
                'parent_id' => 38,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-07-24 08:38:38',
                'updated_at' => '2024-07-24 08:38:38',
            ],
            [
                'id' => 245,
                'name' => 'Ruang Instrument, Mechanical, Process',
                'parent_id' => 39,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2024-07-30 09:43:50',
                'updated_at' => '2024-07-30 09:43:50',
            ],
            [
                'id' => 246,
                'name' => 'Ruang Meeting Rasamala',
                'parent_id' => 44,
                'related_departement' => null,
                'is_active' => true,
                'created_at' => '2017-01-19 09:57:22',
                'updated_at' => '2017-01-19 09:57:22',
            ],
        ];

        $isSqlsrv = DB::connection()->getDriverName() === 'sqlsrv';

        if ($isSqlsrv) {
            DB::unprepared('SET IDENTITY_INSERT locations ON;');
        }

        foreach (array_chunk($records, 100) as $chunk) {
            DB::table('locations')->upsert(
                $chunk,
                ['id'],
                ['name', 'parent_id', 'related_departement', 'is_active', 'updated_at']
            );
        }

        if ($isSqlsrv) {
            DB::unprepared('SET IDENTITY_INSERT locations OFF;');
        }
    }
}
